### ISSUE TITLE
README file is particularly sparse

### ISSUE THREAD

**Issue by zeiphon** [scottabutler/monopoly-bank#1]
More sparse than this issue.

**Comment by zeiphon** [comment]
Any update on this?
Thanks

**Comment by scottabutler** [comment]
Hello @zeiphon,

Thanks for your interest in Monopoly Bank! I have updated the README file per your request and you can see the commit here: https://github.com/scottabutler/monopoly-bank/commit/66ebdc3081271ad9159dd0b4028946782a10519a

Cheers
